"""
Auto-generated fieldMap with Category classes.
Generated by proc_json.py
"""

from generated_categories.admissionsourcedescriptioncategory import AdmissionSourceDescriptionCategory
from generated_categories.admissionstatusdescriptioncategory import AdmissionStatusDescriptionCategory
from generated_categories.datasetcategory import DatasetCategory
from generated_categories.ethnicitycategory import EthnicityCategory
from generated_categories.facilitynamecategory import FacilityNameCategory
from generated_categories.paitentidcategory import PaitentIdCategory
from generated_categories.peergroupcategory import PeerGroupCategory
from generated_categories.primarydiagnosiscategory import PrimaryDiagnosisCategory
from generated_categories.primarydiagnosiscodecategory import PrimaryDiagnosisCodeCategory
from generated_categories.primarydiagnosisdescriptioncategory import PrimaryDiagnosisDescriptionCategory
from generated_categories.primaryprocedurecategory import PrimaryProcedureCategory
from generated_categories.primaryprocedurecodecategory import PrimaryProcedureCodeCategory
from generated_categories.primaryproceduredescriptioncategory import PrimaryProcedureDescriptionCategory
from generated_categories.racecategory import RaceCategory
from generated_categories.readmitdenomcategory import ReadmitDenomCategory
from generated_categories.readmitnumcategory import ReadmitNumCategory
from generated_categories.servicelineversioncategory import ServiceLineVersionCategory
from generated_categories.sexcategory import SexCategory
from generated_categories.shortnamecategory import ShortnameCategory
from generated_categories.vizcohortcategory import VizcohortCategory
from generated_categories.vizcohortlongcategory import VizcohortlongCategory
from generated_categories.vizacuityscaledirectcostcategory import VizAcuityScaleDirectCostCategory
from generated_categories.vizacuityscaleloscategory import VizAcuityScaleLosCategory
from generated_categories.vizacuityscalemortalitycategory import VizAcuityScaleMortalityCategory
from generated_categories.vizbasemsdrgdescriptioncategory import VizBasemsdrgDescriptionCategory
from generated_categories.vizmsdrgdescriptioncategory import VizMsdrgDescriptionCategory
from generated_categories.vizservicelinedescriptioncategory import VizServiceLineDescriptionCategory
from generated_categories.vizsubservicelinecodecategory import VizSubServiceLineCodeCategory
from generated_categories.vizsubservicelinedescriptioncategory import VizSubServiceLineDescriptionCategory
from generated_categories.procedurescategory import ProceduresCategory

fieldMap = {
    'ADMISSION_AGE_YEARS': int,
    'ADMISSION_SOURCE_CODE': int,
    'ADMISSION_SOURCE_DESCRIPTION': str,
    'ADMISSION_STATUS_CODE': int,
    'ADMISSION_STATUS_DESCRIPTION': str,
    'CMI': float,
    'COST_TYPE_CODE': int,
    'DATASET': DatasetCategory,
    'DAYS_TO_READMIT': float,
    'DEATH_FLAG': int,
    'DISCHARGE_STATUS_CODE': int,
    'DISCHARGE_TO_HOSPICE_FLAG': int,
    'DISCH_MONTH': int,
    'DISCH_YEAR': int,
    'DNR_WO_VENT_ECMO_FLAG': int,
    'ENCOUNTER_ID': float,
    'ENC_COUNT': int,
    'ETHNICITY': EthnicityCategory,
    'EXPECTED_DIRECT_COST': float,
    'EXPECTED_LOS': float,
    'EXPECTED_MORTALITY': float,
    'FACILITY_NAME': FacilityNameCategory,
    'HOSPICE_FLAG': int,
    'ICU_DAYS': int,
    'LENGTH_OF_STAY_DAYS': int,
    'LOS': int,
    'LOS_OUTLIER': int,
    'NONVIABLE_NEONATE_FLAG': int,
    'NORMAL_NEWBORN_FLAG': int,
    'OBSERVED_DIRECT_COST': float,
    'PAITENT_ID': PaitentIdCategory,
    'PALLIATIVE_CARE_FLAG': int,
    'PEER_GROUP': PeerGroupCategory,
    'PLANNED_ADMISSION_FLAG': int,
    'PRIMARY_DIAGNOSIS': PrimaryDiagnosisCategory,
    'PRIMARY_DIAGNOSIS_CODE': PrimaryDiagnosisCodeCategory,
    'PRIMARY_DIAGNOSIS_DESCRIPTION': str,
    'PRIMARY_PROCEDURE': PrimaryProcedureCategory,
    'PRIMARY_PROCEDURE_CODE': PrimaryProcedureCodeCategory,
    'PRIMARY_PROCEDURE_DESCRIPTION': str,
    'RACE': RaceCategory,
    'READMIT_DENOM': ReadmitDenomCategory,
    'READMIT_NUM': ReadmitNumCategory,
    'RECORD_ID': int,
    'RELATIVE_EXPECTED_DIRECT_COST': float,
    'RELATIVE_EXPECTED_LOS': float,
    'RELATIVE_EXPECTED_MORTALITY': float,
    'RISK_TYPE_CODE': int,
    'RV_ACUTE_RENAL_FAILURE': int,
    'RV_ADMIT_ED_TRAUMA': int,
    'RV_ANEMIA': int,
    'RV_ANEMIA_IN_CHRONIC_DISEASE': int,
    'RV_BLOOD_LOSS_ANEMIA': int,
    'RV_CACHEXIA': int,
    'RV_CHF': int,
    'RV_CHRONIC_FATIGUE': int,
    'RV_COAGULATION_DEFECT': int,
    'RV_DEMENTIA': int,
    'RV_FLUID_ELECTROLYTE_DISORDERS': int,
    'RV_LIVER_FAILURE': int,
    'RV_MALNUTRITION': int,
    'RV_METASTATIC_CANCER': int,
    'RV_NUTRITIONAL_ANEMIA': int,
    'RV_OBESITY': int,
    'RV_RESPIRATORY_FAILURE': int,
    'RV_SHOCK': int,
    'RV_THROMBOCYTOPENIA': int,
    'RV_TXFER_ACUTE': int,
    'RV_VENT_ON_ADMIT_DATE': int,
    'SERVICE_LINE_VERSION': ServiceLineVersionCategory,
    'SEX': SexCategory,
    'SHORTNAME': ShortnameCategory,
    'SUBSTANCE_ABUSE': int,
    'TRANSFER_IN_FLAG': int,
    'VIZCOHORT': VizcohortCategory,
    'VIZCOHORTLONG': VizcohortlongCategory,
    'VIZ_ACUITY_SCALE_DIRECT_COST': VizAcuityScaleDirectCostCategory,
    'VIZ_ACUITY_SCALE_LOS': VizAcuityScaleLosCategory,
    'VIZ_ACUITY_SCALE_MORTALITY': VizAcuityScaleMortalityCategory,
    'VIZ_BASEMSDRG_CODE': int,
    'VIZ_BASEMSDRG_DESCRIPTION': str,
    'VIZ_MSDRG_CODE': int,
    'VIZ_MSDRG_DESCRIPTION': VizMsdrgDescriptionCategory,
    'VIZ_SERVICE_LINE_CODE': int,
    'VIZ_SERVICE_LINE_DESCRIPTION': str,
    'VIZ_SUB_SERVICE_LINE_CODE': VizSubServiceLineCodeCategory,
    'VIZ_SUB_SERVICE_LINE_DESCRIPTION': str,
    'procedures': ProceduresCategory,
}
