"""
Auto-generated Category subclass: VizMsdrgDescriptionCategory
Generated by generate_category.py
"""

from typing import List
from abstract import Category


class VizMsdrgDescriptionCategory(Category):
    """
    VizMsdrgDescriptionCategory with isolated category tracking.
    
    This class maintains its own separate _categories list,
    independent of the parent Category class and other subclasses.
    """
    
    # Override the shared class variable with a new list for this subclass
    _categories: List[str] = []
    
    def __init__(self, category_name: str):
        # Don't call super().__init__() to avoid parent's _categories
        # Instead, implement the logic directly with our own _categories
        
        if category_name in self._categories:
            self.cat_ord = self._categories.index(category_name)
        else:
            self._categories.append(category_name)
            self.cat_ord = len(self._categories) - 1
    
    @classmethod
    def get_all_categories(cls) -> List[str]:
        """Return all registered categories for this class."""
        return cls._categories.copy()
    
    @classmethod
    def reset_categories(cls):
        """Clear all registered categories for this class."""
        cls._categories.clear()
    
    @classmethod
    def num_categories(cls) -> int:
        """Return the number of registered categories."""
        return len(cls._categories)
